# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends usage stats. If you're concerned about privacy, uncomment the following line.
# disable_cocoapods_analytics!

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.expand_path(File.join('..', '..', '..', 'ios'), __FILE__)
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
